alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
alias docker_clean='docker image ls | grep none | awk '\''{print }'\'' | xargs docker rmi'
alias egrep='egrep --color=auto'
alias fetch='/trading/utils/fetch_data.sh /trading/utils/fetch_list.txt'
alias fgrep='fgrep --color=auto'
alias grep='grep --color=auto'
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -alF'
alias ls='ls --color=auto'
alias python='python3'
alias view='python3 /trading/utils/view_symbol.py'
